//go:build ignore
// +build ignore

package main

import (
	"fmt"
	"os"
)

func main() {
	f, err := os.Create("../tables.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	fmt.Fprintln(f, "package main")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "// Code generated by gen.go; DO NOT EDIT.")
	fmt.Fprintln(f, "")

	// 正方形サイズのみを対象にする
	sizes := []int{4, 8, 12, 16, 24, 32}
	for _, s := range sizes {
		generateAndWrite(f, s, s)
	}
}

func generateAndWrite(f *os.File, rows, cols int) {
	maxN := rows * cols

	fmt.Fprintf(f, "var table%dx%d = [...]coord{\n", rows, cols)

	r, c := 0, 0
	goingUp := true

	for i := 0; i < maxN; i++ {
		fmt.Fprintf(f, "\t{%d, %d},", r, c)

		if (i+1)%8 == 0 {
			fmt.Fprintln(f)
		}

		if goingUp {
			if c == cols-1 {
				r += 1
				goingUp = false
			} else if r == 0 {
				c += 1
				goingUp = false
			} else {
				r -= 1
				c += 1
			}
		} else {
			if r == rows-1 {
				c += 1
				goingUp = true
			} else if c == 0 {
				r += 1
				goingUp = true
			} else {
				r += 1
				c -= 1
			}
		}
	}
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f, "")
}